### ISSUE TITLE
DCGAN / Fashion-mnist Runtime Error

### ISSUE THREAD

**Issue by PeterKim1** [Zeleni9/pytorch-wgan#19]
Hello.

I run your DCGAN, dataset is Fashion-mnist, but this error occur.

Traceback (most recent call last):
  File "/content/drive/MyDrive/pytorch-wgan/main.py", line 42, in <module>
    main(args)
  File "/content/drive/MyDrive/pytorch-wgan/main.py", line 30, in main
    model.train(train_loader)
  File "/content/drive/MyDrive/pytorch-wgan/models/dcgan.py", line 125, in train
    for i, (images, _) in enumerate(train_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/pytorch-wgan/utils/fashion_mnist.py", line 75, in __getitem__
    img = self.transform(img)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 221, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 336, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 32, 32] doesn't match the broadcast shape [3, 32, 32]

After i search your codes, in utils/data_loader.py, transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)) exists.

Fashion-mnist is gray-scale dataset, so it need to set transforms.Normalize((0.5,), (0.5)).

**Comment by Zeleni9** [comment]
Yea I saw the problem, its fixed.
